// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export class TenantUser extends pulumi.CustomResource {
    /**
     * Get an existing TenantUser resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: TenantUserState, opts?: pulumi.CustomResourceOptions): TenantUser {
        return new TenantUser(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'alicloud:ocean/tenantUser:TenantUser';

    /**
     * Returns true if the given object is an instance of TenantUser.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is TenantUser {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === TenantUser.__pulumiType;
    }

    public readonly description!: pulumi.Output<string | undefined>;
    public readonly encryptionType!: pulumi.Output<string | undefined>;
    public readonly instanceId!: pulumi.Output<string>;
    public readonly roles!: pulumi.Output<string | undefined>;
    public readonly tenantId!: pulumi.Output<string>;
    public readonly userName!: pulumi.Output<string>;
    public readonly userPassword!: pulumi.Output<string>;
    public readonly userType!: pulumi.Output<string>;

    /**
     * Create a TenantUser resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: TenantUserArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: TenantUserArgs | TenantUserState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as TenantUserState | undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["encryptionType"] = state ? state.encryptionType : undefined;
            resourceInputs["instanceId"] = state ? state.instanceId : undefined;
            resourceInputs["roles"] = state ? state.roles : undefined;
            resourceInputs["tenantId"] = state ? state.tenantId : undefined;
            resourceInputs["userName"] = state ? state.userName : undefined;
            resourceInputs["userPassword"] = state ? state.userPassword : undefined;
            resourceInputs["userType"] = state ? state.userType : undefined;
        } else {
            const args = argsOrState as TenantUserArgs | undefined;
            if ((!args || args.instanceId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'instanceId'");
            }
            if ((!args || args.tenantId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'tenantId'");
            }
            if ((!args || args.userName === undefined) && !opts.urn) {
                throw new Error("Missing required property 'userName'");
            }
            if ((!args || args.userPassword === undefined) && !opts.urn) {
                throw new Error("Missing required property 'userPassword'");
            }
            if ((!args || args.userType === undefined) && !opts.urn) {
                throw new Error("Missing required property 'userType'");
            }
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["encryptionType"] = args ? args.encryptionType : undefined;
            resourceInputs["instanceId"] = args ? args.instanceId : undefined;
            resourceInputs["roles"] = args ? args.roles : undefined;
            resourceInputs["tenantId"] = args ? args.tenantId : undefined;
            resourceInputs["userName"] = args ? args.userName : undefined;
            resourceInputs["userPassword"] = args ? args.userPassword : undefined;
            resourceInputs["userType"] = args ? args.userType : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(TenantUser.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering TenantUser resources.
 */
export interface TenantUserState {
    description?: pulumi.Input<string>;
    encryptionType?: pulumi.Input<string>;
    instanceId?: pulumi.Input<string>;
    roles?: pulumi.Input<string>;
    tenantId?: pulumi.Input<string>;
    userName?: pulumi.Input<string>;
    userPassword?: pulumi.Input<string>;
    userType?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a TenantUser resource.
 */
export interface TenantUserArgs {
    description?: pulumi.Input<string>;
    encryptionType?: pulumi.Input<string>;
    instanceId: pulumi.Input<string>;
    roles?: pulumi.Input<string>;
    tenantId: pulumi.Input<string>;
    userName: pulumi.Input<string>;
    userPassword: pulumi.Input<string>;
    userType: pulumi.Input<string>;
}
